name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}


      - name: configure QEMU action...
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: configure Docker Buildx...
        id: docker_buildx
        uses: docker/setup-buildx-action@master


      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.docker_buildx.outputs.name }}
          context: .
          file: ./docker_file/Dockerfile
          platforms: linux/amd64,linux/arm,linux/arm64
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: |
            ghcr.io/massimogirondi/github_mirrorer:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
